---
distFolder: ./
setup:
  - name: Setup composer
    action: php-actions/composer@v6
  - name: Setup Node.js v14.x
    action: actions/setup-node@v1
    properties:
      node-version: 14.x
  - name: Make envfile
    action: SpicyPizza/create-envfile@v1
    properties:
      envkey_APP_NAME: Laravel
      envkey_APP_ENV: local
      envkey_APP_KEY: dummy
      envkey_APP_DEBUG: true
      envkey_APP_URL: ${{ steps.project.outputs.site-url }}
      envkey_LOG_CHANNEL: stack
      envkey_LOG_LEVEL: debug
      envkey_DB_CONNECTION: sqlite
      envkey_BROADCAST_DRIVER: log
      envkey_CACHE_DRIVER: file
      envkey_FILESYSTEM_DRIVER: local
      envkey_QUEUE_CONNECTION: sync
      envkey_SESSION_DRIVER: file
      envkey_SESSION_LIFETIME: 120
      envkey_MAIL_MAILER: smtp
      envkey_MAIL_HOST: ${{ secrets.MAIL_HOST }}
      envkey_MAIL_PORT: ${{ secrets.MAIL_PORT }}
      envkey_MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      envkey_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      envkey_MAIL_ENCRYPTION: ${{ secrets.MAIL_ENCRYPTION }}
      envkey_MAIL_FROM_ADDRESS: ${{ secrets.MAIL_FROM_ADDRESS }}
      envkey_MAIL_FROM_NAME: "${APP_NAME}"
      directory: ./
      file_name: .env
build:
  name: Do stuff to deploy to ionos
  command:
    sudo chown runner:docker .env;
    chmod -R 777 storage/framework;
    chmod -R 777 storage/logs;
    php artisan key:generate --force;
    npm ci;
    npm run prod;
    php artisan migrate --force;
